#include "receiver.h"
#include <stdlib.h>
#include <math.h>
#include <float.h>


// we are going to use the box muller method to generate one gaussian sample



static float gaussian() {  // static to not be used from other function and be used only here (perivate helper function)

	float u1, u2, z; // u1 and u2 uniform random nbrs between 0 and 1 

	do {

       		do { u1 = (float)rand() / (float)RAND_MAX; } while ( u1 == 0.0f); // u1 =/= 0 because later logf(u1) -- rand_max is the biggest random generated by gcc we divide by it to get a number ranges between 0 and 1 and this what the box muller requires

		u2 = (float)rand() / (float)RAND_MAX;

		z = sqrtf(-2.0f * logf(u1)) * cosf(2.0f * (float)M_PI * u2); // box muller formula

	} while (z < -5.0f || z > 5.0f); // we make the random distribution between 5 and -5  

	return z;

}



// here we add the noise to the X_N received signal 
// sigma in the strength of the noise that will be computed in the main.c from the SNR
// sigma in multiplied with the gaussian sample

void channel_AWGN_add_noise(const int32_t *X_N, float *Y_N, size_t N, float sigma) {
	for (size_t i = 0; i < N; i++) {
		// we cast X_N to a float because Y_N is a float
		Y_N[i] = (float)X_N[i] + (sigma * gaussian());
	}
}


void modem_BPSK_demodulate(const float *Y_N, float *L_N, size_t N, float sigma) {
	for (size_t i = 0; i < N; i++) {
		L_N[i] = Y_N[i];
	}
}

void codec_repetition_hard_decode(const float *L_N, uint8_t *V_K, size_t K, size_t n_reps) {
	for (size_t i = 0; i < K; i++) {
		int one = 0; // how many reps decided bit=1
		
		for (size_t r = 0; r < n_reps; r++) {
			if (L_N[(r * K) + i] < 0.0f)
				one ++;
		}


		V_K[i] = (one > (int)(n_reps / 2)) ? 1 : 0;
	}
}


void codec_repetition_soft_decode(const float *L_N, uint8_t *V_K, size_t K, size_t n_reps) {
	for (size_t i = 0; i < K; i++) {
		float sum = 0.0f;


		for (size_t r = 0; r < n_reps; r++) {
			sum += L_N[(r * K) + i];
		}

		float mean = sum / (float)n_reps;

		V_K[i] = (mean < 0.0f) ? 1 : 0;
	}
}	

void monitor_check_errors(const uint8_t *U_K, const uint8_t *V_K, size_t K, uint64_t *n_bit_errors, uint64_t *n_frame_errors) {

	uint64_t frame_err = 0;

	for (size_t i = 0; i < K; i++) {
		if (U_K[i] != V_K[i]) {
			(*n_bit_errors)++;
			frame_err++;
		}
	}

	if (frame_err > 0)
	       (*n_frame_errors)++;
}	








































